import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

import { Audiowide } from "next/font/google";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";
const audiowide = Audiowide({ subsets: ["latin"], weight: ["400",], variable: "--font-audiowide" });



export const metadata: Metadata = {
  title: "Srbija RealEstate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={audiowide.className}>
        <AuthProvider>

          <Navbar />
          {children}
          <Footer />
        </AuthProvider>

      </body>
    </html>
  );
}
